# Main story publishing worker
name = "slopnews-news-agent"
main = "src/index.ts"
compatibility_date = "2024-02-20"

routes = [
  { pattern = "news-agent.slop247.com", custom_domain = true }
]

[[d1_databases]]
binding = "slopnews_db"
database_name = "slopnews_db"
database_id = "14a69182-cb40-4f74-9985-c0ee6c8d8eb1"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "slopnews-images"