import {
  HEADER_HTML,
  FOOTER_HTML,
  SHARED_STYLES,
  SHARED_SCRIPTS,
} from './components.js';

export const DISCLAIMER_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Disclaimer - SLOP News 24/7</title>
    <meta name="description" content="Southern Louisiana Operationalized Partition - Disclaimer">
    <meta name="keywords" content="news, Louisiana, Southern Louisiana, operational news, partition analysis">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="SLOP News 24/7">
    <meta property="og:title" content="Disclaimer - SLOP News 24/7">
    <meta property="og:description" content="Southern Louisiana Operationalized Partition - Disclaimer">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@SLOP News 24/7">
    <style>
        ${SHARED_STYLES}
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 20px;
        }
        .disclaimer {
            margin: 2rem 0;
            font-size: 1.2rem;
            line-height: 1.6;
        }
        .back-link {
            display: inline-block;
            margin: 2rem 0;
            color: #333;
            text-decoration: none;
        }
        .back-link:hover {
            color: #666;
        }
    </style>
</head>
<body>
    ${HEADER_HTML}
    <div class="container">
        <a href="/" class="back-link">← Back to home</a>
        <div class="disclaimer">
            <h1>Disclaimer</h1>
            <div>All content on this website—including articles, images, headlines, and the site itself—is generated by artificial intelligence (AI) and is intended for entertainment and research purposes only. The stories, events, and individuals depicted on this site are entirely fictional, even if they reference real-world events or people. Any resemblance to actual persons, living or dead, or actual events is purely coincidental or a parody of actual fact and personalties.</div>
            <br />
            <div>This site does not publish factual news or real reporting. No information on this site should be interpreted as factual, accurate, or a reflection of real-world events. The creators and operators of this site make no representations or warranties regarding the accuracy, reliability, or authenticity of any content presented herein.</div>
            <br />
            <div>By using this site, you acknowledge and agree that all content is AI-generated fiction and should not be relied upon for any purpose other than entertainment or research.</div>
            <br />
            <div>If you have questions or concerns about any content, please contact us at [your contact email].</div>
        </div>
    </div>
    ${FOOTER_HTML}

    <script>
        ${SHARED_SCRIPTS}
        // Initialize navigation and headlines when the page loads
        window.addEventListener('load', () => {
            console.log('Page loaded, initializing...');
            renderNavigation();
            updateHeadlinesMarquee();
        });
    </script>
</body>
</html>`;
