name = "slopnews-website"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "slop247.com", custom_domain = true },
  { pattern = "www.slop247.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "slopnews_db"
database_id = "14a69182-cb40-4f74-9985-c0ee6c8d8eb1"

[dev]
port = 8787
